# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".ruby-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Phil Burrows' Blog
tagline:
author :
  name : Phil Burrows
  email : dev@philburrows.com
  github : peburrows
  twitter : peburrows

google :
  tracking_id : 'UA-3699362-2'

production_url : http://peburrows.github.io


archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

comments :
  provider : disqus
  disqus :
    short_name : peburrows